#!/bin/bash

#	set -xv

SRC_DIR="./build/libs"
DEST_DIR="./testing environment/mods"
file=$(ls -dtr1 "$SRC_DIR"/* | tail -1)

if [[ "$(find "$file" -mmin +1)" == '' ]]; then
	./gradlew build
fi
cp -puv "$file" "$DEST_DIR"

#(cd "$DEST_DIR" && ls -tp | grep -v '/$' | grep 'StructuredModLoader' | tail -n $(expr 1 + 1) | xargs -I {} rm -v -- {})
