modLoader="javafml"
loaderVersion="[39,40)"
license="GPL-3.0"
issueTrackerURL="github.com/Chaos02/SubFolderLoader/issues"

[[mods]]
modId="structuredmodloader"
version="${file.jarVersion}"
displayName="StructuredModLoader"
updateJSONURL="github.com/Chaos02/SubFolderLoader/update.json"
displayURL="github.com/Chaos02/SubFolderLoader"
logoFile="StructuredModLoader.png"
credits="" 
authors="Chaos_02" 
description='''
Loads mod files from configurable subfolders 
to provide cleaner modpack structure
'''

[[dependencies.structuredmodloader]]
    modId="forge"
    mandatory=true
    versionRange="[39,40)"
    ordering="NONE"
    side="BOTH"
[[dependencies.structuredmodloader]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
