modLoader="javafml"
loaderVersion="[39,40)"
license="GPL-3.0"
issueTrackerURL="https://github.com/Chaos02/SubFolderLoader/issues"
showAsResourcePack=false

[[mods]]
modId="smlforgemod"
version="${file.jarVersion}"
displayName="StructuredModLoader"
updateJSONURL="https://raw.githubusercontent.com/Chaos02/SubFolderLoader/main/update.json"
displayURL="https://github.com/Chaos02/SubFolderLoader"
logoFile="StructuredModLoader.png"
credits="stiebi99#2124 on Discord without whom it would not have been possible to create this mod!" 
authors="Chaos_02" 
description='''
Loads mod files from configurable subfolders 
to provide cleaner modpack structure
'''

[[dependencies.smlforgemod]]
    modId="forge"
    mandatory=true
    versionRange="[39,40)"
    ordering="NONE"
    side="BOTH"
[[dependencies.smlforgemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
